### ISSUE TITLE
Documentation Links not valid

### ISSUE THREAD

**Issue by davelovemartin** [rudibatt/Magento-ExportExtension#5]
Please updated your links to the Documentation on README

**Comment by rudibatt** [comment]
Urgh... I guess it's deleted from the forum. I can't find it (and I can't even login) anymore, so I will have to write a new one. 
But I haven't used it for some years now... Has anybody an working configuration I can use as a reference?

**Comment by rudibatt** [comment]
Ok, I've wrote it from scratch by investigating the code, but I haven't tested it. I hope it works. Let me know if you find a bug at the doc. Thx.
